# Beautiful Jekyll Theme
remote_theme: daattali/beautiful-jekyll@6.0.1

# Site Settings
title: Benedikt Schackenberg
description: "Just an IT guy."
url: "https://schackenberg.com"
baseurl: ""

# Author
author: Benedikt Schackenberg

# Avatar/Logo
avatar: "/assets/images/benedikt.jpg"
round-avatar: true

# Navigation bar links
navbar-links:
  About: "about"
  Projects: "projects"
  Blog: "blog"
  GitHub: "https://github.com/BenediktSchackenberg"

# Social network links
social-network-links:
  github: BenediktSchackenberg
  email: "benedikt@schackenberg.com"

# Timezone
timezone: "Europe/Berlin"

# Reading files
include:
  - _pages

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - CNAME

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

# Front matter defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      show-avatar: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      show-avatar: true
